# --- Application configuration ---
spring.application.name=${APP_NAME:base-template}
server.port=${SERVER_PORT:9000}
server.servlet.context-path=${SERVER_CONTEXT_PATH:/api/v1}

# --- Logging configuration ---
logging.level.org.springframework=${LOG_LEVEL_ORG_SPRINGFRAMEWORK:INFO}
logging.level.base.template=${LOG_LEVEL_APP:DEBUG}
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} - %logger{36} - %msg%n
logging.file.name=${LOG_FILE_NAME:logs/application.log}
logging.file.max-size=${LOG_FILE_MAX_SIZE:10MB}
logging.file.max-history=${LOG_FILE_MAX_HISTORY:30}
logging.file.total-size-cap=${LOG_FILE_TOTAL_SIZE_CAP:1GB}

# --- DDBB configuration ---
spring.datasource.url=jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:template_db}
spring.datasource.username=${DB_USER:dev_user}
spring.datasource.password=${DB_PASSWORD:dev_password}
spring.datasource.driver-class-name=org.postgresql.Driver

# --- JPA configuration ---
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# --- Flyway configuration ---
spring.flyway.enabled=${FLYWAY_ENABLED:true}
spring.flyway.baseline-on-migrate=${FLYWAY_BASELINE_ON_MIGRATE:true}

# --- Cache configuration ---
spring.data.redis.host=${REDIS_HOST:localhost}
spring.data.redis.port=${REDIS_PORT:6379}

# --- Docker configuration ---
spring.docker.compose.file=${DOCKER_COMPOSE_FILE:docker-compose.yml}
spring.docker.compose.lifecycle-management=start-and-stop

# --- i18n ---
spring.messages.basename=${MESSAGES_BASENAME:i18n/messages}
spring.messages.encoding=${MESSAGES_ENCODING:UTF-8}
spring.messages.fallback-to-system-locale=false

# --- Security configuration ---
security.jwt.secret=${JWT_SECRET}
security.jwt.access-expiration-minutes=${JWT_ACCESS_EXPIRATION_MINUTES:15}

security.jwt.refresh-cookie-name=${JWT_REFRESH_COOKIE_NAME:jwt-token}
security.jwt.refresh-expiration-days=${JWT_REFRESH_EXPIRATION_DAYS:7}

# --- Configuración de Swagger ---
springdoc.api-docs.path=${SPRINGDOC_API_DOCS_PATH:/v3/api-docs}
springdoc.swagger-ui.path=${SPRINGDOC_SWAGGER_UI_PATH:/swagger-ui.html}
